### ISSUE TITLE
Sprites used are missing

### ISSUE THREAD

**Issue by pnorman** [versatiles-org/versatiles-style#12]
The download files have `https://tiles.versatiles.org/assets/sprites/sprites` as a sprite URL. This results in a request to https://tiles.versatiles.org/assets/sprites/sprites.json or https://tiles.versatiles.org/assets/sprites/sprites@2x.json, both of which are missing

The styles on tile.versatiles.org use https://tiles.versatiles.org/sprites/sprites

There might be a similar font issue, but it looks to be more complex.

**Comment by MichaelKreil** [comment]
We switched to new sprites, but versatiles.org is not updated yet.

**Comment by pnorman** [comment]
A related problem to the missing file is that some sprites are missing from the online files, like icon-car_wash, but are present in the releases.

**Comment by MichaelKreil** [comment]
Yes, I already combined the generation of sprites and styles, so we can verify that every sprite is available and used.

**Comment by MichaelKreil** [comment]
We updated tiles.versatiles.org a while ago and everything seems to be fine now.
