### ISSUE TITLE
Missing fonts

### ISSUE THREAD

**Issue by pnorman** [versatiles-org/versatiles-style#13]
colorful.json uses the font `noto_sans_regular`, which does not exist at the glyph location https://tiles.versatiles.org/assets/fonts/{fontstack}/{range}.pbf

Changing the font to `Noto Sans Regular` and the glyph location to `https://tiles.versatiles.org/fonts/{fontstack}/{range}.pbf` works.

**Comment by yetzt** [comment]
michael chose to rename the fonts to lowercase and without spaces initially. currently we are overhauling that part of the stack and we will be fixing the styles eventually.

**Comment by MichaelKreil** [comment]
The new font folder structure is already generated, see [repo](https://github.com/versatiles-org/versatiles-fonts) and [doc](https://github.com/versatiles-org/versatiles-documentation/blob/main/basics/compendium.md#versatiles-frontend-specifications).
I just need to update the frontend and deploy the new version.

**Comment by MichaelKreil** [comment]
We updated tiles.versatiles.org a while ago and everything seems to be fine now.
