### ISSUE TITLE
Broken sprites

### ISSUE THREAD

**Issue by tumic0** [versatiles-org/versatiles-style#22]
![sprites](https://github.com/versatiles-org/versatiles-style/assets/11480505/5f7e62d3-be58-4957-b55f-3402f6b7b75a)

I really doubt that the sprites (that's the original 1x PNG from the archive) shall look that blured. To me it seems like the sprite PNG generation is broken.

**Comment by MichaelKreil** [comment]
No, they are correct. They are special SDF sprites (signed distance fields), can be recoloured in the frontend, and render sharply at any resolution.
Here is an article on how they work: https://docs.mapbox.com/help/troubleshooting/using-recolorable-images-in-mapbox-maps/
