### ISSUE TITLE
Font issue

### ISSUE THREAD

**Issue by x7ci** [versatiles-org/versatiles-style#4]
I think there's an issue with RTL text - the characters in the labels are in reversed order. This can also be seen on https://tiles.versatiles.org/colorful.html

Maybe it's because of the "Noto Sans Regular" font?

**Comment by MichaelKreil** [comment]
Hm. It looks fine to me.
Could you post a screenshot?

**Comment by x7ci** [comment]
See the middle eastern or african country labels for example - the country names are reversed:
![1](https://github.com/versatiles-org/versatiles-styles/assets/122831534/f6bc9780-19ce-4f67-9b0a-1127b7f8946d)

**Comment by x7ci** [comment]
Seems it's an easy fix - we just load the RTL plugin for MapLibre. Maybe the versatiles demo page should also have this?

https://maplibre.org/maplibre-gl-js/docs/examples/mapbox-gl-rtl-text/

**Comment by MichaelKreil** [comment]
Thanks! We will add the plugin into the frontend
